### ISSUE TITLE
Problem with `log_and_raise`

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#125]
**Describe the bug**

The `vr.core.logger.log_and_raise` function turns out to have a weakness for some kinds of exceptions. At the moment, it is:

```python
def log_and_raise(msg: str, exception: Type[Exception], extra: Optional[dict] = None) -> None:
    """Emit a critical error message and raise an Exception. """

    LOGGER.critical(msg, extra=extra)
    raise exception(msg)
```
The problem is that the `__init__` methods for exceptions can take other arguments in addition to the message. 
In the current implementation, the exception gets stripped of the context that generated it and a new instance is created, which is fine until there is more than just the message to creating the new instance. The example I ran into is `json.JSONDecodeError`:

```python
In [134]: import json
     ...: from virtual_rainforest.core.logger import LOGGER, log_and_raise
     ...: 
     ...: try:
     ...:     json.loads("[not][json]")
     ...: except json.JSONDecodeError:
     ...:     log_and_raise('test', json.JSONDecodeError)
     ...: 
[CRITICAL] - logger - log_and_raise(37) - test
...
TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'
```

So, I think a better implementation is 

```python
def alternative_lr(excep: Exception, message: Optional[str] =None):

    if message is not None:
        excep.args = (message,)

    LOGGER.critical(message or excep)
    raise excep
```

That can just be used directly with the trapped exception:

```python
In [136]: try:
     ...:     json.loads("[not][json]")
     ...: except json.JSONDecodeError as exc:
     ...:     alternative_lr(exc)
     ...: 
[CRITICAL] - <ipython-input-130-1c2ac073bde1> - alternative_lr(2) - Expecting value: line 1 column 2 (char 1)
...
JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

And better targeted messages can still be inserted:

```python
In [137]: 
     ...: try:
     ...:     x = int('a')
     ...: except ValueError as excep:
     ...:     alternative_lr(excep, "Not an integer")
     ...: 
     ...: 
[CRITICAL] - <ipython-input-136-6385a41d7aaa> - alternative_lr(6) - Not an integer
...
ValueError: Not an integer
```

But - any better ways of doing this? @dalonsoa and @alexdewar

**Comment by alexdewar** [comment]
I think you're thinking along the right lines with the `alternative_lr` implementation. Ideally when you're doing things like this you want to re-raise the original exception (or raise a new one "from" it) so that you're not throwing away information and you can get a proper stack trace etc.

I don't think you need this bit though:

```py
    if message is not None:
        excep.args = (message,)
```

I'm just a bit concerned about possible side effects from mucking about with the original exception instance. Your devs will be able to see your bespoke error message from the log anyway.

Another alternative is to raise a new exception "from" the old one as I mentioned, e.g.:

```py
raise VirtualRainforestError(msg) from excep
```

That way you can include `msg` with the exception while not discarding info about the stack etc.

**Comment by davidorme** [comment]
Yeah - the replacement of the args bothered me too. Also, we do have another common use pattern:

```python
if condition_that_indicates_something has gone_wrong:
    log_and_raise("Something went wrong", AppropriateError)
```

In this case, we have an Exception type, not an actual raised Exception instance. So then:

```python
def alternative_lr(excep: Union[Exception,????], message: Optional[str] =None):

    # If excep is not an exception instance, create one using the stated exception type:
    if not isinstance(excep, Exception):
        excep = excep(message)

    # emit a log message, either using the exception message itself or an optional alternative note
    LOGGER.critical(message or excep)

    # Raise the exception
    raise excep
```

I'm not 100% clear on what the type of unraised Exception class is!

**Comment by alexdewar** [comment]
I would definitely have two different functions for this rather than trying to make one function that does everything.

What we've been talking about so far is the one I'd call `log_and_reraise`. For the `log_and_raise` function, I'd swap the order of arguments around, e.g.:

```py
log_and_raise(ValueError, "arg is out of range")
```

Then you would have a function definition that looks something like this:

```py
def log_and_raise(cls: Type[BaseException], *args: Any, **kwargs: Any) -> None:
    excep = cls(*args, **kwargs)
    LOGGER.critical(excep)
    raise excep
```

Yes, this does mean you'd have to go through the code and change every line where you've done a `log_and_raise` (`mypy` is your friend here). This will be a bit of a pain given that you have a load of code not currently in `develop` (this will need fixing up), but that's another reason why ideally you want to try to merge your code in small chunks as you go along.

**Comment by davidorme** [comment]
I agree - I think this is much cleaner. We were going to have to change those lines anyway: it's a fairly straightforward job.

**Comment by davidorme** [comment]
@alexdewar @dalonsoa I've implemented the functions discussed above in a feature branch (b654a01) **BUT** one thing we hadn't considered here is that these helpers *divert the location of the exception and message* in a way that I think is actively harmful. 

@jacobcook1995  and I  adopted this from a package that used it to produce a single simple report that did not need to retain any information about where in the code the messages came from and was not meant to provide users with a stack trace on Exceptions.

However here both the logs and stack trace are relevant for all users and these functions raise and log from within the `logger.py` module, so we get a log message like this:

`[CRITICAL] - logger - log_and_raise(90) - One on't cross beams gone owt askew on't treddle.` 

And then traceback like this:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dorme/Research/Virtual_Rainforest/virtual_rainforest/tests/test_logger.py", line 14, in test_log_and_raise
    log_and_raise(RuntimeError, "One on't cross beams gone owt askew on't treddle.")
  File "/Users/dorme/Research/Virtual_Rainforest/virtual_rainforest/virtual_rainforest/core/logger.py", line 91, in log_and_raise
    raise excep
RuntimeError: One on't cross beams gone owt askew on't treddle.
```

That is not helpful. There are easy ways to edit the logger message using `extra` to modify the logging message but that would be a an irritating cost for every use of "convenience" functions and I can't see any easy way to "re-locate" the traceback. So, I now think we should simply **remove `log_and_raise`** and replace it with one of these two patterns for re-raise or raise:

```python
try:
    doing_something_that_raises()
except ValueError as excep:
    LOGGER.critical(excep)
    raise
```

```python
 if thing_has_gone_wrong:
      excep = ValueError("It went wrong!")
      LOGGER.critical(excep)
      raise excep
```

**Comment by alexdewar** [comment]
I think being explicit as you suggest is probably the way to go. The helpers really don't add much. At most you're saving one line of typing and mandating that users use the `critical` log level, which often may not be appropriate. Exceptions aren't always fatal in Python.

I'm surprised `log_and_raise` doesn't work the way you want it to though. Is it not giving the full stack trace?

As I mentioned before, in Python where you catch an exception then raise another you can express it like this:

```py
try:
    run_thing()
except RuntimeError as e:
    raise ValueError("Bad input") from e
```

This should preserve the stack trace of `e`. Calling `raise excep` to re-raise an exception is *not* the way to achieve this. You can also just use `raise` without an argument to re-raise the last exception (as you've done).

**Comment by davidorme** [comment]
OK - so the action needed now is to review all uses of `log_and_raise` and replace as appropriate.

**Comment by dalonsoa** [comment]
Nothing to add except supporting the change to avoid the convenient-but-not-helpful-function and use explicit `try...except...`

**Comment by davidorme** [comment]
@alexdewar @dalonsoa 

In this pattern:

```python
try:
    doing_something_that_raises()
except RuntimeError as excep:
    LOGGER.critical(excep)
    raise ValueError("Bad input") from excep
```

There is a slight difference in what is going into the logger and what is being raised. I can't see how to get the new exception from `excep` for use in the logger _before_ actually raising the new exception? Is there a way?

It is hardly the biggest deal in the world :smile:

**Comment by davidorme** [comment]
Aw come _on_! ``mypy`` objects to that second pattern following an `if`:

```
Assignment to variable "excep" outside except: block  [misc]mypy(error)
```

I do really know what I'm doing and I am genuinely creating an exception with the intention of raising it.
