### ISSUE TITLE
core.constants.py

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_rainforest#129]
Different modules will need access to a core set of constants such as density of air, Stephan Bolzman constant,...

Proposed solution: centrally stored dictionary core.constants.py

**Comment by davidorme** [comment]
I think that makes sense as a mini module. Another possibility for the contents - which I used over in `pyrealm` - is to use  `dataclasses.dataclass`. There are a couple of possible advantages:

* You can freeze the contents, so no-one can accidentally edit them.
* It gives you a slightly neater access method (`constants.density_of_air` not `constants['density_of_air']`)

**Comment by dalonsoa** [comment]
The second point is easily covered by by putting all the constants in a module and using it as `from vr.core import constants`. Granted that it does not prevent importing specific constants nor to edit them, but it seems like the most straight forward approach. 

Either way (data class or module) will work fine. My main concern always with universal constants are units. What units they will be defined in? How is that communicated to the users? I tried [a not-so-popular approach](https://github.com/qpv-research-group/solcore6/blob/develop/solcore/constants.py) in a project some time ago using `pint`, but yet it might work here.

**Comment by davidorme** [comment]
Completely agree about care needed on units. There are various python solutions for units such as `pint` and `cfunit` but it does add a layer of complexity - I've also seen pushback against using coded units. We certainly should state them in docs/comments and perhaps we park whether to actually programatically set them for now?

**Comment by davidorme** [comment]
Closing - see #364
