### ISSUE TITLE
Sphinx not rendering bullets from RST correctly

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#143]
For some reason - and I don't think it is simply getting the RST syntax wrong because I've tried all combinations under the sun - `sphinx` is refusing to render bulleted lists correctly. The list items just come out as a set of paragraphs in the HTML.

_Originally posted by @davidorme in https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/122#discussion_r1082659648_

**Comment by davidorme** [comment]
I think it may be something to do with this:

https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

On local builds, I get some unordered lists rendering correctly but - oddly - not all of them. The *module* docstring for `core.data` contains an UL that renders fine on my local machine but not on ReadTheDocs, but the *class* docstring for `core.axis.AxisValidator` and *method* docstring for `core.data.Data.load_data_config` contain ULs that do not render either locally or on RTD.

**Comment by dalonsoa** [comment]
I'm sorry if it is just me being dumb, but I'm trying to build the documentation locally (with `make html` in the `docs` directory) to diagnose this and I end up with errors that build down to:

```error
[ERROR] - manager - wrapper(89) - No such kernel named vr_python3
```

I did `git pull` in the develop branch  followed by `poetry install` to get the latest dependencies (with the versions indicated in the lock file) without success.

Am I missing anything here?

**Comment by dalonsoa** [comment]
Ok, solved. I missed this line https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/6f2da0defc3a839b901f5f96afa694c3737c3f22/.readthedocs.yaml#L24

Is this documented anywhere?

**Comment by davidorme** [comment]
It is documented, but only in the context of using `jupyter` and that is clearly not separable from the `sphinx` building :

https://virtual-rainforest.readthedocs.io/en/latest/development/jupyter_notebooks.html

I _think_ this is necessary, but I might have missed a way to do something like `poetry run jupyter-lab` and have it use the poetry environment as the `ipykernel` whilst in the `poetry run` shell.

**Comment by davidorme** [comment]
Raised #144
