### ISSUE TITLE
Testing models

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_rainforest#166]
We need to test the higher level model classes, where should we do this? At the moment, a number of tests are combined in `test/test_models.py` but this might soon become overcrowded.

Should we split the file to test for each Model individually or keep it as one file? Some functionalities will be the same for all models, maybe tests could be combined.

**Comment by dalonsoa** [comment]
In complex projects, I normally keep for the tests the same folder/file structure than in the actual code. In that sense, I would restructure completely the location of the tests to follow that. I'm sorry I did not spot this back at the beginning, when starting to write the tests.

**Comment by davidorme** [comment]
Wait  - I just launched issue #168 directly from this issue. I could have sworn I was reading this message in a PR. Sorry.
