### ISSUE TITLE
Restructure the `tests` folder.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#168]
The `tests` folder has a very flat structure, which is going to get confusing fast. @dalonsoa has pointed out:

> In complex projects, I normally keep for the tests the same folder/file structure than in the actual code. In that sense, I would restructure completely the location of the tests to follow that. I'm sorry I did not spot this back at the beginning, when starting to write the tests.

_Originally posted by @dalonsoa in https://github.com/ImperialCollegeLondon/virtual_rainforest/issues/166#issuecomment-1422476713_

**Comment by jacobcook1995** [comment]
So would the intended file structures be e.g. `tests/test_core/test_config.py` and `tests/test_models/test_soil/test_carbon.py`?

**Comment by davidorme** [comment]
Probably just `tests/core/test_config.py` and `tests/models/soil/test_carbon.py`?

**Comment by vgro** [comment]
I would go with @davidorme 's version, but I think both would work

**Comment by jacobcook1995** [comment]
I was just wondering if `pytest` would pick up intermediate folders without the `test_*` structure? If it does then @davidorme's version definitely works better

**Comment by vgro** [comment]
good point, this I don't know

**Comment by dalonsoa** [comment]
Yes, the `test_` is only needed on the files, not on the intermediate folders. `pytest` will pick all of those files as containing tests, no matter the folder structure.

**Comment by TaranRallings** [comment]
Would we be keeping the model.py tests in the central `test_models.py` file or decentralize those tests into something like `tests/models/animals/test_model.py`?

**Comment by jacobcook1995** [comment]
The latter. That was actually the exact file that sparked this issue.
