### ISSUE TITLE
Broken `mypy` configuration in `pre-commit`

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#170]
**Describe the bug**

We have an issue with our `mypy` setup in pre-commit:

* Within `poetry run` or `poetry shell` we are running `mypy` along with a bunch of additional packages that get installed by our poetry setup.
* However, within `pre-commit` we only install `mypy` and none of the other dependencies, so it misses some typing issues because there are types it doesn't know about.

This is a known thing - see discussion here: https://github.com/pre-commit/mirrors-mypy/issues/3

It is also the reason why we sometimes get `mypy` errors indicated in VSCode but `pre-commit` waves the file through. If you manually run `mypy` on a file with those errors using the project virtual environment (`poetry run mypy path/to/file.py`) then you get those errors highlighted.

So the basic issue is that there are two _separate_ virtual environments being used: `pre-commit` maintains its own _venvs_ separate from the project one. We can fix this in one of two ways:

1. Specify all the `additional_dependencies` in the `.pre-commit-config.yaml`.

   This is then basically duplicating the virtual environment used by `poetry shell` in the `pre-commit` virtual environment.  This is probably more correct but it is a pain:
   * it has to be kept up to date with `pyproject.toml`, and 
   * it also isn't obvious to me which packages in `pyproject.toml` need adding here. All of them?

3. We could configure `.pre-commit-config.yaml` just to use the `system` version of `mypy`:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        language: system
```

This is risky in some circumstances - who knows what version is going to be run - but I think within a `poetry` managed virtual environment it works safely. But... I may be missing something!

**To Reproduce**
Tricky - basically make a commit that uses something like `xarray` types?

**Expected behavior**
Consistent `mypy` reporting

**Comment by davidorme** [comment]
@dalonsoa and @alexdewar - have you had to fix this kind of thing before? It doesn't seem like there is an obvious or simple synchronisation approach.

**Comment by davidorme** [comment]
@davidorme This is a test message for seeing what Slack and GH Desktop integrations do about messages.

**Comment by dalonsoa** [comment]
Yes, we have, and the less problematic solution is Option 1. See what we did for another project: https://github.com/ImperialCollegeLondon/FINESSE/blob/1a79f817945092aca6210c9864172854639e3fa6/.pre-commit-config.yaml#L25

There are strong calls to the developer of `pre-commit` to start using `pyproject.toml` and the dependencies listed therein like everybody else, but he refuses... Until someone forks the project and create an alternative `pre-commit` that does it.

**Comment by davidorme** [comment]
Is there a simple way to work out which dependencies need to go in there? It isn't just `types`, I think?

**Comment by dalonsoa** [comment]
I can't tell. Our use cases had always been just types, but I guess there might be other packages that need to go there, too. I'm not sure if @alexdewar might have a suggestion about figuring that out.

**Comment by davidorme** [comment]
It's a pain to do by trial and error - because `pre-commit` is being more permissive you basically have to find errors that get flagged in VSCode but that `pre-commit` waves through. I guess the simple answer is include _all_ of them. I wonder why the developer has an issue with using `pyproject.toml`...
