### ISSUE TITLE
Community standards: Add LICENSE

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#20]
This is a must for a public repository. In case of doubt, use a restrictive one like GPL because you can always make it less restrictive. The other way around is harder. 

Check Imperial College Information on the topic:

[Open source software licences | Administration and support services | Imperial College London](https://www.imperial.ac.uk/enterprise/staff/industry-partnerships-and-commercialisation/commercialisation/intellectual-property-guidance/open-source-software-licences/)

More on Community Standards: [Community Standards (github.com)](https://github.com/ImperialCollegeLondon/virtual_rainforest/community)

**Comment by jacobcook1995** [comment]
Closed by #109
