### ISSUE TITLE
Allowing "constants" to vary

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#209]
**Is your feature request related to a problem? Please describe.**
A lot of the constants that we have defined are not true constants. In the case of the soil module a lot of them are regression outputs from previous empirical studies. The sensitivity of these "constants" will therefore obviously needed to be tested, so they will need to be alterable in some way.

**Describe the solution you'd like**
I don't really have a clear idea of a solution to this beyond redefining what we call a "constant" once it comes time to do sensitivity analysis. I think this is something we should discuss in detail at some point.

**Additional context**
[David's description of the problem.](https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/206#pullrequestreview-1400640673)

**Comment by davidorme** [comment]
I'd argue that #210 is the _same_ issue. We have a bunch of things that must not change during a run. Some of those must not change _ever_ (Boltzmann etc) but I'm not sure there is any useful mileage in having a separate container for "constants"  and **constants**.

What I have done over in `pyrealm` is create frozen `dataclass` bundles of both kinds of constants, so a high level function takes that container and passes it down as needed to lower level functions. At the bottom of the stack, functions and methods should probably take the required individual constants as arguments, as @dalonsoa described as good practice. That is actually something I need to fix in `pyrealm`, which passes the `dataclass` bundle all the way to the bottom. The freezing stops anything* from modifying the contents once the constants `dataclass` instance is created before the run.

* Anything that isn't a deliberately malicious attempt to subvert the frozen status, anyway.
