### ISSUE TITLE
Define the format and contents of the sensitivity analysis (SA) input file

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#240]
This input file will define which parameters are to be varied, by how much and what is the valid range for them. If more than one parameter is to be varied, the space to explore will be a matrix, a cube, etc. for 2, 3 or more parameters. 

The parameter(s) to vary need to be any of the ones available in the VR input file (see for example [data/example_config.toml](https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/develop/data/example_config.toml)). At the moment there's no much as the models are still in the process of being implemented, so this issue is more about creating the relevant documentation for creating this sensitivity analysis input file as well as a JSON schema file to validate this file. The suggested format for this SA file would be `toml`, as that's the format for the VR configuration file.

Note that the schema will validate if the SA file has the correct sections, but not if the values for the parameters to vary are valid - that's the job for the relevant validation steps when running the simulation. The schema might also be used to spot parameters that are forbidden to vary in any meaningful sensitivity analysis - and that, therefore, should not be in the SA file. That would be the case, for example, the parameters related to the definition of the grid or the vertical layers.

An initial version of the python script to write in #241 will be implemented here just to load the SA file and validated with the JSON schema. This script will be defined as an additional entry point for VR in here: https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/33226a0c7b91db1ffe7a1d32aa529199e51a5bd9/pyproject.toml#L14

For each parameters, the information that might be required is:
- parameter to vary (full "path" where it can be found in the VR config file)
- initial value to use (eg. `25`)
- valid range for the parameter (eg. `[10, 45]`) -> So the range is 35
- percentages of the range to vary the parameter by (eg. `[0.05, 0.1, 0.15]`) will vary the parameter `25` by ±5% of 35, ±10% of 35 and ±15% of 35, so 7 values in total including `25`; if the value falls outside of the valid range, it will be discarded) -> if many points are needed, we could replace this by what `np.linspace` takes as input: start, stop, points.

Questions:
- What parameters MUST never be allowed to vary?
- Is this approach of defining the parameter space correct?

**Comment by jacobcook1995** [comment]
I don't *think* that anything in the `core` config is going to be a valid target for sensitivity analysis. At the moment, it defines the timing, grid size, number of layers, data output options, and where to load variables from.

It seems reasonable to me that we would include every variable we want to plausibly expose for sensitivity analysis in the configurations for individual models. At the moment, the `soil` config section is empty because I've hardcoded all parameters in, but this would be a sensible place to add variables in to move away from hardcoding, keeping the stuff where we are pretty certain of values hardcoded.

It probably bears mentioning that the `soil` model is likely to be structurally the simplest model, so other models needs might well be very different here. What are other people's views?

**Comment by davidorme** [comment]
I think the first thing we need to solve here is the common structure of constants classes and their packaging and how constant values can be varied. Each model at the moment has taken a broadly similar but not completely aligned approach to defining packages of constants and there is no way to alter those values. We need to have a consistent mechanism to override those constants from within the model configuration before we can do sensitivity analysis.

It is possible that this work could be a precursor to the SA work? Either way, there are a lot of existing discussions and issues that touch on this - we probably need a sprint or similar to sort this out:

See:
Discussion item #162 (basically summarised below!)
Issue #210
Issue #209
Issue #129

I think the basic structure we have to work with is that the `vr` constants are defined as a tree and we should probably systematically create `core.constants' and `models.example_model.constants` modules where all constants are defined. That then gives a consistent path with the code structure that we can use in `toml` config files.

Each module should then use one mechanism (probably a frozen `dataclass`) to create sets of constants objects that can be instantiated by `from_config` methods and attached to the model instance. I think that this probably means that each model `__init__` needs to take all of the constants classes as input parameters?

So then a user can do:

```toml
[plants.constants.pmodel_constants]
phi0 = 0.123
```

And then in `from_config` 

```python
const_config = config['plants']['constants']
if 'pmodel_constants' in const_config:
    pmodel_const = PModelConstants(**const_config['pmodel_constants'])
else:
    pmodel_const = PModelConstants()

...

return PlantsModel(..., pmodel_const = pmodel_const, ...)
```

As an aside, I don't see the value in discriminating between 'true constants' and 'other constants'. All of these values are part of a single tree of constants and splitting them into two trees with different mechanisms seems overkill. It doesn't make any sense to change the Universal Gas Constant but I think it is cleaner to have a single framework for constants.

**Comment by dalonsoa** [comment]
Ok, I had assumed that you already had this sorted and it was just as simple for us as hooking into whatever you had in place. If that is not the case, then I agree that's preliminary work that needs to be done - by us or by you, I don't mind. 

On your last point, I disagree. I think it is useful to have truly universal constants defined in one single place that all models can look into when they need their value. It avoids errors I've seen sometimes of, for example, using those constants with a different number of decimals. 

About the actual implementation, your suggestion looks sensible, although I'm not sure I understand the nesting of `plants.constants.pmodel_constants`. Why not just `plants.constants`? And then:

```python
return PlantsModel(..., constants = PModelConstants(**config['plants'].get("constants", {})), ...)
```

**Comment by dalonsoa** [comment]
Ah, ok, I get it. And why not one set of constants per module (one for plants, one for animals, etc.)? I was trying to avoid too much nesting, I think it always makes things more messy, but I guess it makes sense. 

So, if a constant of interest is in `core.constants`, how does the - let's say - plants models access it? I don't see how the code you showed above could make that constant available to the Plant model.

**Comment by davidorme** [comment]
I would argue for as few sets of constants per model as possible and one would be ideal - but there is always going to be some case (size of sets, thematic grouping) that breaks that ideal, so I think not having the layer of nesting is too restrictive.

Good point about access that instantiated constants module. At the moment it is just imported, but now it would have to be passed down. My first thought was to make it a property of the `Config` object, which gets passed down to models, but it might be clearer to simply make it an argument of `BaseModel.__init__()` and children. One central constants class that gets created in `core` setup and then passed down, so it is clearer to keep it separate from other objects.

**Comment by alexdewar** [comment]
I think this issue is redundant if we use Snakemake to run SA workflows. Either we express the inputs (i.e. parameters to be varied) directly in a Snakefile or we write some Python helper functions for this to be used by the Snakefile. In both cases, we won't need extra TOML files to express the parameter grid.

Are people happy for me to close this?

**Comment by davidorme** [comment]
@jacobcook - There's some important stuff in here about the constants classes and passing that information through the simulation that is independent of using that approach with SA. Can you quickly review that we've captured the behaviour/information in the rollout of the updated constants systems?

**Comment by jacobcook1995** [comment]
Yeah I think we have, like the design we adopted is basically the one you mentioned in this comment.

> I think the first thing we need to solve here is the common structure of constants classes and their packaging and how constant values can be varied. Each model at the moment has taken a broadly similar but not completely aligned approach to defining packages of constants and there is no way to alter those values. We need to have a consistent mechanism to override those constants from within the model configuration before we can do sensitivity analysis.
> 
> It is possible that this work could be a precursor to the SA work? Either way, there are a lot of existing discussions and issues that touch on this - we probably need a sprint or similar to sort this out:
> 
> See: Discussion item #162 (basically summarised below!) Issue #210 Issue #209 Issue #129
> 
> I think the basic structure we have to work with is that the `vr` constants are defined as a tree and we should probably systematically create `core.constants' and `models.example_model.constants`modules where all constants are defined. That then gives a consistent path with the code structure that we can use in`toml` config files.
> 
> Each module should then use one mechanism (probably a frozen `dataclass`) to create sets of constants objects that can be instantiated by `from_config` methods and attached to the model instance. I think that this probably means that each model `__init__` needs to take all of the constants classes as input parameters?
> 
> So then a user can do:
> 
> ```toml
> [plants.constants.pmodel_constants]
> phi0 = 0.123
> ```
> 
> And then in `from_config`
> 
> ```python
> const_config = config['plants']['constants']
> if 'pmodel_constants' in const_config:
>     pmodel_const = PModelConstants(**const_config['pmodel_constants'])
> else:
>     pmodel_const = PModelConstants()
> 
> ...
> 
> return PlantsModel(..., pmodel_const = pmodel_const, ...)
> ```
> 
> As an aside, I don't see the value in discriminating between 'true constants' and 'other constants'. All of these values are part of a single tree of constants and splitting them into two trees with different mechanisms seems overkill. It doesn't make any sense to change the Universal Gas Constant but I think it is cleaner to have a single framework for constants.

And we also have generally kept the number of constants class to a minimum without enforcing only one per model, which was what the subsequent conversation was about
