### ISSUE TITLE
Facilitate producing a pbs submission script for Imperial's HPC

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#242]
After producing the collection of input config files in #241 , a submission script for Imperial's HPC will be created such that it can launch the execution of VR running all of those files as an array job.

A [Jinja2](https://jinja.palletsprojects.com/en/3.0.x/templates/) template of the submission script will be created. The relevant fields in the template will be replaced by the specific values of the given SA.

As part of this issue, the SA input file (and related schema) could be modified to include the configuration of the HPC run, such as the requested memory, wall time, etc.

This will be a feature useful specifically for running the sensitivity analysis at Imperial's HPC. It needs to be discussed if the VR is the right place for this tool or if it should be kept in a separate repository. 

Questions:
- Do we want to include the HPC-related inputs in the SA file?
- Do we want to include the creation of the PBS submission script, Imperial-specific in this repo?

**Comment by alexdewar** [comment]
Superseded by #276.
