### ISSUE TITLE
Document and/or enforce model update order

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#247]
**Is your feature request related to a problem? Please describe.**
At the moment, the order at which models are called in for each process (i.e. `setup`, `update`) is set by the order of the `modules` list in the config. So, if `modules = ["abiotic_simple", "hydrology", "soil"]` then the `abiotic_simple` model is updated first, then the `hydrology` model, and then the `soil` model.

Some models cannot be updated before other models. At present, if the first update of the `soil` model happens before the first update of the `abiotic_simple` model the simulation will stall as an undefined soil temperature will be passed to the integrator which then silently fails. The user isn't currently given an indication as to why the simulation has stalled.

**Describe the solution you'd like**
We need to document the order in which models can be run somewhere. We also need to inform the user that an invalid order has been entered. We also might want to change the `core.modules` config option to make it more obvious that this sets the model update (etc) order, or alternatively remove this control from the config system entirely. I can't think of any obvious solution for all this atm, and think that it's something worth discussing as a group.

**Describe alternatives you've considered**
Alternatively, we could rewrite the models so that they can be setup, updated, etc, in any order. However, suspect this might be quite complex to do for minimal gain.

**Comment by davidorme** [comment]
Closed by #352 which introduced the model order settings into the configuration
