### ISSUE TITLE
Fix time_index in dummy climate data

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_rainforest#256]
Climate data is accessed via `isel(time_index=time_index)`. The dummy climate data currently has the coordinated `time` and `time_index`, but only one dimension which is `time_index`. This was created by renaming the `time` dimension, which is a bit of a hack. This is not of high priority,  I will find a solution when I have some time to test.

**Comment by davidorme** [comment]
I've just run into this when integrating the plant model.

**Comment by davidorme** [comment]
The specific issue here was addressed in #339
