### ISSUE TITLE
Constants registry to document default values

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#259]
**Is your feature request related to a problem? Please describe.**
The default value of constants are currently only documented in the API docs, which fundamentally are not user facing. They should be documented in a way that most users can view 

**Describe the solution you'd like**
As suggested by @davidorme constant classes could be added to a unit registry. This could then be used to create a default constant values documentation page.

**Describe alternatives you've considered**
Not sure that there's an obvious alternative for documenting the constants

**Comment by davidorme** [comment]
Using a registry also makes for a neater programmatic interface for validating user configuration of constants classes:
https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/258#discussion_r1267911971

**Comment by davidorme** [comment]
And also make a helper function for validating constant classes:
https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/260#discussion_r1272501628

**Comment by jacobcook1995** [comment]
A constants registry has been added so this can be closed
