### ISSUE TITLE
Add example config files to the repo

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#265]
As part of my work on #239, I want to be able to produce an example script (or snakemake file) to show how to run a SA. The problem is that the data is not part of this repo (and contains hardcoded paths; see #264) and ideally I don't want to produce an example that requires getting data files from elsewhere.

Given that the data doesn't seem sensitive, it might make sense to just add these config files to this repo. Yes, there are some binary files in there, but they are tiny, so the filesize isn't worth worrying about IMO.

It's nice for users to be able to run an example directly from a repo directly, without having to try to obtain the data from elsewhere or construct their own based on the docs.

**Comment by davidorme** [comment]
Good idea and the file sizes are indeed tiny. We should avoid changing them around too much obviously!

Over in `pyrealm` I followed a suggestion from @dalonsoa of having a second package within the project to contain `pyrealm_build_data`. We could do that with `vr_demo_data` package, which could then be imported and used in `docs` (and maybe `tests`), but which users could also import and access. Makes for nice path discovery via `importlib` for one thing.

**Comment by alexdewar** [comment]
@davidorme That's a good idea. It means if anyone downloads it e.g. over PyPI they still get the example data.
