### ISSUE TITLE
Common VSCode settings

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#27]
How to setup the cod editor is a rather personal thing, but it is useful to have a common set of settings or tools adding the coding. For the `.vscode/settings.json` file, I would suggest to have the following:

```json
{
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.mypyEnabled": true,
    "python.linting.enabled": true,
    "python.formatting.provider": "black",
    "editor.formatOnSave": true,
    "workbench.tree.indent": 24,
    "editor.rulers": [
        88
    ],
    "files.autoSave": "afterDelay",
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.pytestArgs": [
        "-s",
        "tests"
    ],
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "rewrap.autoWrap.enabled": true,
    "editor.wordWrapColumn": 88,
```

The suitability of these options should be discussed and some of them might need further configuration in VSCode, like installing another extension or a dev-dependency.

**Comment by alexdewar** [comment]
For any additional extensions needed, you can also consider adding them to
``extensions.json`` so they'll be recommended to developers.
