### ISSUE TITLE
Tests fail if simulation output files present in project root

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#272]
**Describe the bug**
If any output files with the default names are present in the root of the VR folder, a couple of the unit tests fail:

```
============================== short test summary info ===============================
FAILED tests/test_main.py::test_merge_continuous_data_files - virtual_rainforest.core.exceptions.ConfigurationError: A file in the user specifi...
FAILED tests/test_main.py::test_merge_continuous_file_already_exists - virtual_rainforest.core.exceptions.ConfigurationError: A file in the user specifi...
===================== 2 failed, 464 passed, 35 skipped in 10.13s =====================
```

**To Reproduce**
```sh
touch all_continuous_data.nc
pytest
```

**Expected behavior**
The tests should pass regardless of the state of the local filesystem.

**Comment by jacobcook1995** [comment]
Ahh yeah I think those are both tests that I wrote. So, is the proper strategy to creating a temporary directory (one with a name that's unlikely to ever be used?) for the test and then saving everything there and deleting everything at the end of the test?

**Comment by davidorme** [comment]
Nope  - use `pytest-datadir` which does all that automatically.

**Comment by jacobcook1995** [comment]
Oh and with `tests/core/test_data.py::test_save_timeslice_to_netcdf` if the file `continuous1.nc` exists
