### ISSUE TITLE
Need to decide whether to supply default values from constants

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#277]
**Is your feature request related to a problem? Please describe.**
Before we introduced the new system for constants we wrote a lot of functions that defined default values imported from the relevant `constants.py` module, e.g.

```python
def calculate_max_sorption_capacity(
    bulk_density: NDArray[np.float32],
    percent_clay: NDArray[np.float32],
    coef: MaxSorptionWithClay = MaxSorptionWithClay(),
) -> NDArray[np.float32]:
```

If constants are supplied like this then they will not change when the value of the constant is changed during simulation configuration. This introduces the risk of us forgetting to populate a constant in a function call, and then the default value getting used (in e.g. a sensitivity analysis) without the user knowing. On the other hand it's poor code style to not set defaults for functions with a large number of arguments.

**Describe the solution you'd like**
We could decide to avoid suppling default values for constants to functions, to avoid this risk.

**Describe alternatives you've considered**
We could still supply default constant values and just be careful to never invoke functions without all constants specified in the main function flow.

Alternatively, there might be a way to populate these default values from the constants registry, which would avoid the problem entirely.

I think this is something we should discuss as a group so we can agree upon a common strategy, and then document accordingly.

**Comment by davidorme** [comment]
Closing - see #364
