### ISSUE TITLE
Importing `virtual_rainforest` package always causes models to be loaded

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#278]
Currently if you import the `virtual_rainforest` package, all models are loaded (which is slow) and lots of log output is produced, even though the models are not necessarily needed. For example, if you run `vr_run --help`, you get this output.

This isn't currently a problem (though it would be nice if the output of `vr_run --help` weren't so ugly), but we may wish to add additional commands to `vr_run` or make `virtual_rainforest` usable as a library in some way, in which case this will become annoying.

**Comment by davidorme** [comment]
The intention behind this was to auto discover all models and make sure registries are populated and schema are discovered. There is very little that can be done with the model until that has happened, so sticking it in `__init__.py` made a lot of sense, but as the suite of tools and entry points we support increases, that is going to be happening prematurely.

I think we basically need to wrap this step up into a `discover_models` function - but having that as a mandatory step before you can run a model also seems a bit clunky. 

The immediate logical place to put that step might be within the `Config` set up:

- You _have_ to have a `Config` object to run a model.
- You have to have loaded all the models to validate the configuration.
- It delays model loading until a step that logically precedes running a model.

So if this happens automatically as a method of `Config`? The thing I can't remember is whether the model tests necessarily go through the config process? The sequence is awkward.

**Comment by alexdewar** [comment]
That makes sense.

Would it work to have the model discovery step be done explicitly in `vr_run()`? In the short term, it may be sufficient to just move various `import`s into the body of `vr_run()`.

**Comment by davidorme** [comment]
We could do that but I think it would be better if the model loading happened as a part of standard operation - like creating the `Config` - rather than as part of a longer recipe. That is primarily so that programmatic use of the library is more logical/cleaner. Short term, we could use a `vr_run` recipe, but I don't think that's a natural place for it.

**Comment by davidorme** [comment]
That makes sense but I was wondering if we can make SCHEMA_REGISTRY itself a bit smarter and import modules? The advantage to that is that we can just use `SCHEMA_REGISTRY["my_model"]` to trigger the import.  I think the argument for this is that then we don't even have to create a Config to ensure that a model is loaded, which I think might be useful in some of the tests?

Something like this? I haven't tested it at all 😄 

```python
class SchemaRegistry(dict):

    def __getitem__(self, __key: Any) -> Any:

        if __key in self:
            return super().__getitem__(__key)

        try:
            import_module(f"virtual_rainforest.models.{__key}")
        except Exception as excep:
            LOGGER.error(f"Error while loading '{__key}' model: {str(excep)}")
            raise

        return super().__getitem__(__key)

SCHEMA_REGISTRY = SchemaRegistry()
```

One thing that might be a problem there is that `self` is modified by the module import while `__getitem__` is executing - would the last line in the method actually access that updated value?

**Comment by davidorme** [comment]
I think it works. If I modify that so that `import_module` is just a simple function to modify `SCHEMA_REGISTRY`:

```python
class SchemaRegistry(dict):

    def __getitem__(self, __key: Any) -> Any:

        if __key in self:
            return super().__getitem__(__key)

        try:
            extend_sr(__key)
        except Exception as excep:
            LOGGER.error(f"Error while loading '{__key}' model: {str(excep)}")
            raise

        return super().__getitem__(__key)

SCHEMA_REGISTRY = SchemaRegistry()

def extend_sr(ky):

    SCHEMA_REGISTRY[ky] = ky * 3
```

Then:

```python
In [12]: SCHEMA_REGISTRY
Out[12]: {}

In [13]: SCHEMA_REGISTRY['gone']
Out[13]: 'gonegonegone'

In [14]: 
```

**Comment by jacobcook1995** [comment]
Yeah definitely think moving away from importing every model is sensible. The current approach was just a stop gap I added because I couldn't come up with a more elegant way to make sure that `MODEL_REGISTRY` and `SCHEMA_REGISTRY` contained the models when `vr_run` was called

**Comment by alexdewar** [comment]
@davidorme Yes, that's the kind of thing I had in mind.

I would say though that we don't want to be overriding magic methods where we don't have to. How about just adding a regular function to load/get the schemas? I don't think anyone should be using `SCHEMA_REGISTRY` directly outside of `config.py` anyhow.

**Comment by alexdewar** [comment]
> @alexdewar Avoiding overriding methods because it is less clear that something else happens beyond the getting?

Yeah, exactly. That's always the problem with operator overloading: the person reading the code won't necessarily notice that there's some extra magic going on under the hood.

I'm not sure that it really does need to be a method of `SCHEMA_REGISTRY` tbh, though that's less important. You could just have a standalone function:

```python
def get_schema(model: str) -> dict:
    try:
        import_module(f"virtual_rainforest.models.{model}")
    except Exception as excep:
        LOGGER.error(f"Error while loading '{model}' model: {str(excep)}")
        raise

    return SCHEMA_REGISTRY[model]
```

Hmm?

**Comment by davidorme** [comment]
Actually, I think we'd need to catch `ModuleNotFoundError` exceptions in that, but everything else is/should be handled by the `__init_subclass__` and `register_schema` code.

**Comment by alexdewar** [comment]
@davidorme Agreed.

The only thing I would add is that you can get exceptions other than `ModuleNotFoundError` when trying to load a module, i.e. if the module itself raises an exception for some reason. So I think it would be worth printing an error message to this effect for all exceptions thrown.

**Comment by davidorme** [comment]
That's true - the exception handling we already have in those subroutines will get passed back up to here, so we could discriminate between exceptions specific to `mod` being unknown and other downstream stuff going wrong.

```python
def load_models(models: tuple[str]) -> None:
    for mod in models:
        try:
            import_module(f"virtual_rainforest.models.{mod}")
        except ModuleNotFoundError:
            LOGGER.critical(f"Unknown model name: {mod}")
            raise
        except Exception as excep:
            LOGGER.critical(f"Error on loading model {mod}: {str(excep)}")
            raise
```

**Comment by davidorme** [comment]
Ugh. Fixing this turns out to be a hideous morass of circular imports - with the existing autodiscovery, a whole load of stuff gets imported right at the start. Delaying the registration until later generates long chains of importing that become circular (particularly `config` and `base_model`) - there's quite a lot of tinkering to fix this. I also don't think it makes sense to tackle this separately from #302
