### ISSUE TITLE
Update `check_valid_constant_names`

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#297]
**Is your feature request related to a problem? Please describe.**

At the moment, we have code like this in `BaseModel.from_config` methods:

```python
if "plants" in config and "constants" in config["plants"]:
    # Checks that constants is config are as expected
    check_valid_constant_names(config, "plants", "PlantsConsts")
    # If an error isn't raised then generate the dataclass
    constants = PlantsConsts(**config["plants"]["constants"]["PlantsConsts"])
else:
    # If no constants are supplied then the defaults should be used
    constants = PlantsConsts()
```

The `check_valid_constant_names` function accesses all of the information and classes used in getting the constant class information here, so we could move this inside the helper function and let it return the instantiated ConstantsClass, reducing the `from_config` code to just:

```python
constants = get_validated_constants(config, "plants", "PlantsConsts")
```

We should also update `check_valid_constant_names` to use the new Constants registry.

**Comment by jacobcook1995** [comment]
Isn't this already handled in #295 ?

**Comment by davidorme** [comment]
Ah - so it is. Sorry! Trying to track too many moving targets with not enough coffee
