### ISSUE TITLE
Single registry for all models 

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#302]
**Is your feature request related to a problem? Please describe.**
At the moment there are 3 separate registries used for model setup: `SCHEMA_REGISTRY` which contains the schema required to validate configurations for each model, `CONSTANTS_REGISTRY` which contains the constants classes for each model, and `MODEL_REGISTRY` which contains uninitialised instances of each model. 

**Describe the solution you'd like**
@alexdewar suggested consolidating these registries into a single registry:

2. Given that we're only allowing users to register one model class per module (which I think is sensible!), you could move the model registration code out of `BaseModel.__init_subclass__`...
3. ...and once you've done that you will have all the model registration code in one place (i.e. for model class, schema and constants). Then you can put all of this information into a single model registry object, which should simplify things:

```py
@dataclass
class ModelInfo:
    cls: type[BaseModel]
    schema: dict[str, Any]
    constants: WhateverTypeThisIs

model_registry: dict[str, ModelInfo]
"""Information about models, keyed by name."""
```

_Originally posted by @alexdewar in https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/295#pullrequestreview-1595301552_

**Describe alternatives you've considered**
The main thing to think about is whether `core` belongs in this combined registry. `core` will have a constants class, and the `core` schema is currently stored in `SCHEMA_REGISTRY`, **but** it doesn't define a model (because it isn't a model).

**Comment by davidorme** [comment]
Just to add that when this happens, it would be good to include a logger step in `register_model`, because at the moment the log doesn't seem to note when this happens and that would be useful.
