### ISSUE TITLE
Consider dropping Python 3.9

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#324]
**Is your feature request related to a problem? Please describe.**

There are a bunch of new typing related syntaxes that are available from 3.10. The snakemake helper is moving towards 3.10+ and it might make sense to also update `vr` itself.

Before we start making releases (soon!), we probably want to push the codebase to support only the most recent Python versions, rather than tying us to legacy versions that were only used while the project was in `alpha` development.

**Describe the solution you'd like**

* Drop Python 3.9
* Update syntax to use newer features (see comment: https://github.com/ImperialCollegeLondon/virtual_rainforest_snakemake_template/issues/21#issuecomment-1742693120)

**Describe alternatives you've considered**
Keep Python 3.9

**Comment by jacobcook1995** [comment]
If there's a tool to help with the upgrade then I think we should just go ahead and drop 3.9 support, would the idea be to keep the pre-commit hook permanently?

**Comment by davidorme** [comment]
I think so - I don't know if `pyupgrade` integrates with `poetry` to only trigger when the `python` versions are changed, or if it continually prompts to adopt more modern syntax? And, if so, how it sets what the lowest version supported is. @alexdewar ?

**Comment by alexdewar** [comment]
It doesn't detect the minimum Python version -- you have to tell it what to use as a baseline via a command-line argument.

**Comment by davidorme** [comment]
Ah ok - so we'd configure it in `pre-commit` as:

```yaml
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
    -   id: pyupgrade
    -   args: [--py310-plus]
```

And then it would just keep poking us if we use older syntax.

**Comment by alexdewar** [comment]
Indeed. It doesn't just poke you though, it fixes most (all?) issues it finds. I've found it super helpful.
