### ISSUE TITLE
`test_vr_run` failing all unit tests of logger output to fail

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#331]
**Describe the bug**
If the `test_vr_run` test (found in `tests/core/test_cli_integration.py`) fails then every unit test that compares logged output also fails. This is pretty annoying as it really clogs the screen.

**To Reproduce**

1. Do something that breaks `test_vr_run`, e.g. delete one of the example files in `virtual_rainforest/example_data/`
2. Run `pytest`
3. Sit back and enjoy your terminal filling with ~150 failed unit tests.

**Expected behavior**
Only `test_vr_run` should fail

**Desktop (please complete the following information):**

- OS: macOS
- Version 13.6

**Comment by davidorme** [comment]
Oh - is _that_ what is going on in my registry branch? That might explain a few things!

**Comment by davidorme** [comment]
What I'm seeing is that individual test files pass but running the full suite does this:

```
FAILED tests/[... blah blah blah ...] - assert 9 == 0
```

Is that what you're getting too? Any idea what it is - wait... does the test log to a file? Is it the logfile not being turned off.

**Comment by jacobcook1995** [comment]
Yeah that's exactly what I get, it only happens when `test_vr_run` fails. The log file created by that test not being closed if it fails feels like a plausible source of the problem to me

**Comment by davidorme** [comment]
Does commenting out the logger lines fix it for you?

```python
vr_run_cli(
    args_list=[
        str(example_dir),
        "--outpath",
        str(example_dir),
        # "--logfile",
        # str(example_dir / "vr_example.log"),
    ]
)
```

It certainly helps with the issues I'm seeing! I think what is happening is that the logfile implementation intercepts all the logging messages that normally go to the StreamHandler, so if it that file handler isn't removed, all the log messages continue to be diverted.

**Comment by davidorme** [comment]
On balance, I'd like to retain those lines (and maybe add an assertion or two to check the log exists and maybe ends with Similulation complete. That means we need to implement a teardown method for when that test fails that explicitly removes the file logger.

**Comment by jacobcook1995** [comment]
Yep commenting those lines out fixed the problem, but do agree that retaining those lines + checking for the existence of the log file makes sense
