### ISSUE TITLE
Include core constants as an attribute of each model constants class 

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#342]
**Is your feature request related to a problem? Please describe.**
It's fiddly to have to track both model constants and core constants data-classes separately. So it would be simpler for each model constants data class to contain every relevant constant. By including the core constants data class as an attribute we can also retain the advantage of having a single location where all core constants are defined.

**Describe the solution you'd like**
Core constants could be set as an attribute and relevant constants could be returned using properties, e.g. 

```python
class LitterConsts:
    ...
    core_constants: CoreConsts = CoreConsts()

    @property
    def depth_of_active_soil_layer(self) -> float:
        return core_constants.depth_of_active_soil_layer
```

Then when constants data classes are created from the `Config`, the `CoreConsts` would have to be created first, and used to created the model specific constants data classes.

**Describe alternatives you've considered**
I don't see a clear alternative aside just putting up with each model having a separate `core_constants` and a `model_constants` dataclass.

**Additional context**
[This thread](https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/341#discussion_r1400393462) contains discussion of the issue. Also this issue has overlap with the broader issue #208.

**Comment by davidorme** [comment]
Closing this. Over in #364, we've found a clean solution to implement this, but at the moment have chosen to keep separate `CoreConsts` and `ModelConsts` namespaces, probably with the addition of making a single `CoreConsts` instance at startup to use across all models.
