### ISSUE TITLE
Soil moisture isn't actually needed in the Virtual Rainforest simulation

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#345]
**Is your feature request related to a problem? Please describe.**
At the moment the `hydrology` model calculates soil moisture, but none of the other models actually need to use it. At the moment, the soil model uses it to calculate amount of water in the topsoil layer, something the `hydrology` model could return instead.

**Describe the solution you'd like**
The `hydrology` model could get rid of the soil moisture calculation, and just return the quantity the `soil` model needs instead. It might be worth retaining the soil moisture calculation function, as this is a nice output to have though.

**Comment by vgro** [comment]
For clarification, we keep the soil moisture variable but instead of a relative water content, we calculate absolute water content in mm at a given depth.
