### ISSUE TITLE
Check docstrings as part of pre-commit, CI etc.

### ISSUE THREAD

**Issue by alexdewar** [ImperialCollegeLondon/virtual_rainforest#36]
This is just a suggestion, but I've done it for our own projects and found it useful.

There are various tools you can use to do this, but I've been using
``flake8-docstring``.

You can configure it to e.g. mandate docstrings for public functions, which would help
catch problems like #30.

Just a suggestion!

**Comment by davidorme** [comment]
We've just adopted it on another project (https://github.com/ImperialCollegeLondon/safedata_validator) and we should definitely use it here.
