### ISSUE TITLE
Documentation fails to build complaining about vr-python3 not found

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_rainforest#49]
**Describe the bug**
Try to build the documentation and it fails with:

```bash
Exception occurred:
  File "/Users/dalonsoa/Documents/Projects/virtual_rainforest/.venv/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 294, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named vr_python3
```

**To Reproduce**

Assuming you have the virtual environment activate, just run:

```bash
cd docs
make clean
make html
```

**Expected behavior**
The documentation should build without issues.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Version [e.g. 22] 12.4

**Additional context**
Using the plain develop branch with last commit dab354486

**Comment by davidorme** [comment]
See here: https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/develop/docs/source/development/jupyter_notebooks.md#jupyter-lab

I'm not sure if this is solved by using the poetry venv in project setting. I have a feeling that there is still a local path issue. I may be over engineering this though. I commonly do.
