### ISSUE TITLE
`dependabot` isn't currently recommending updates for all dependencies

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#587]
**Is your feature request related to a problem? Please describe.**
At present `dependabot` isn't recommending updates for all our dependencies. Had to fix a problem with `pre-commit` in #576 that was due to us using a version that was 2 major versions behind. My guess is this is because `dependabot` only checks dependancies in the main `poetry` group.

**Describe the solution you'd like**
@davidorme suggested (based on [this](https://github.com/dependabot/dependabot-core/issues/5766)) that adding `allow: - dependency-type: all` to the `dependabot` config should fix the problem.

**Comment by jacobcook1995** [comment]
Hmm other dependancies in the same group have actually been updated by `dependabot`, so I don't think this is what is causing the issue. I'll close this issue as it's misleading

**Comment by davidorme** [comment]
Yeah - i was just thinking the same. Don't know why `pre-commit` got skipped.
