### ISSUE TITLE
Github actions mypy build check fails when python 3.9 typing is used

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#66]
**Describe the bug**
When the inbuilt type notation introduced in python 3.9 (e.g. `list[str]`) is used, the `pre-commit/action@v2.0.2` fails the [mypy build check](https://github.com/ImperialCollegeLondon/virtual_rainforest/runs/8016565392?check_suite_focus=true). This is despite it passing the pre-commit hook locally.

**To Reproduce**

1. Add a type hint which indexes a collection type (e.g. `list[str]` or `tuple[int]`) to existing code
2. Commit this code
3. If it passes the pre-commit hooks push the code
4. The GitHub actions build check should fail with a message similar to `error: "list" is not subscriptable, use "typing.List" instead`

**Expected behavior**
The mypy build check should pass as we have set our supported python to be >=3.9.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.5.1

**Comment by davidorme** [comment]
I think we just need to add a `python-version` section to the `qa` job

**Comment by davidorme** [comment]
Yeah - the `ubuntu-latest` is Ubuntu 20.04, which includes Python 3.8, so that is what is being used:

https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#:~:text=In%2020.04%20LTS%2C%20the%20python,base%20system%20is%20Python%203.8.

**Comment by davidorme** [comment]
OK, so I think we'll just need to add an extra step:

```yaml
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
```

I think it makes sense to just use the lowest version we want to support.
