### ISSUE TITLE
Simplify grid cell indexing system

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#79]
**Is your feature request related to a problem? Please describe.**

As noted [here](https://github.com/ImperialCollegeLondon/virtual_rainforest/pull/69#discussion_r964375433), using a dictionary of grid cells and using grid position strings (e.g. `grid.cell_dict['1-1']`) as keys is complex (and likely slow).

**Describe the solution you'd like**

In that comment @dalonsoa suggested nested lists and using nested integer indexing (so `grid.cell_list[x_idx][y_idx]`), but just having a single integer index may be even simpler (so `grid.cell_list[cell_id]`). So, a square grid might get cell ids:

```
6 7 8
3 4 5
0 1 2
```

Advantages:

* A single integer points to the cell - shorter code, as above.
* It is easier to map cells to neighbours: cell 4 has rook neighbours `[1, 3, 5, 7]` and not `[(1,0),(0,1),(2,1),(1,2)]`.
* It makes it easy to have spatial layouts that don't conform to a regular grid. Even with hex grids, the x indices are offset for alternate rows, but we could equally have 'grids' with cells of irregular size and shape (way down the development path!).

One open question is how to map cell id on to stored data on the grid. For the square grid - which is going to be our main use case - some operations could run most efficiently on a 2D grid (`numpy` and `scipy` - things like distance), so keeping spatial data as a 2D array (and providing a `grid.map` attribute that converts cell id to numpy indices) is simple. However data loading _could_ unravel all spatial data onto a single axis so that cell id is also the index onto the data.

**Comment by dalonsoa** [comment]
I think this approach makes identifying neighbours much harder than the string key as there is no relationship between the indices of neighbours. If I'm in cell 6, there's no way for me to know what my 4 neighbours are unless I know also nx and ny and do some calculation. 

I still think that a nested list or a pandas dataframe could be a better choice.

**Comment by davidorme** [comment]
I completely agree that the neighbour id is harder. I haven't really set out the full case very well 😄 . This would also involve extending the `Grid` class to provide a neighbour lookup and a distance function. 

* Neighbour lookup is populated when a `Grid` instance is created and is just a list using the same integer index. So `grid.neighbours[6]` returns `[3, 7]`. And a `Grid.set_neighbours(edges=True)` method to set population options.
* The `Grid` object also stores cell centroids, and provides `grid.distance_from(cell_id=[4])` to return `[1.4, 1, 1.4, 1, 0, 1, 1.4, 1, 1.4]`. Or possibly also `grid.cells_within(dist=1)`. 

So, the `Grid` class then is the engine for finding spatial relationships between cells.

**Comment by dalonsoa** [comment]
I've the feeling that you should be using an existing tool to manage these sort of relationships, like [NetworkX](https://networkx.org/documentation/stable/index.html). I don't know for sure, but I suspect we are re-inventing the wheel for some reason with this. I think that your grid could be seen as a network of nodes located at the centre of the cells, and so you could use the full power of a library like the one I mention to manage their location.

**Comment by davidorme** [comment]
I think we may well use `NetworkX` - I have used it extensively before and it is great. We could well represent the cell connectivity as a `networkx.Graph` object, although we still need to develop our own methods to build the graph. The nodes are just the cells but we would need to implement something to define edges.

One thing to balance here is the simple need for immediate neighbours (rook, queen, knight move definitions are common), which is quite compact and works well as a list of lists or a `Graph` object, or the ability to get precise euclidean distances between cells. Those are not calculated particularly accurately using paths through a graph, and are better calculated directly from cell centroids (hence those distance functions). 

We could of course make a *complete* graph of the cells (or equivalently the full cell x cell distance matrix) at startup and then just have everything else as a lookup. But that could be quite a big object? 10000 cells x 10000 cells = 381 Mb as float32).

Unless we go for a complete graph of the cells (which would be quite a big object

**Comment by dalonsoa** [comment]
If you have used NetworkX before then you know way better than me what it offers that might be useful and save some complexity overall. Totally up to you. It is clear that there are pros and cons in both cases. Maybe keeping things as they are now is the simplest approach if there are no obvious gains.

As an alternative to the string key and the single index key, what about a tuple key, eg. `(1, 7)`? The key contains accurate cell location and it will be faster than transforming things to strings. Tuples are perfectly fine keys for Python dictionaries.

**Comment by davidorme** [comment]
I've done a bad job of describing the gains, I think, and I'm not showing how the integer indices might work with `numpy` to give some clean interfaces.

I don't care about having the cell id value convey location information. We are going to have to do a lot of spatial stuff efficiently and actually using the cell id value as the source of location information makes it work too hard. The motivation behind what I'm proposing is to make the `Grid` object the source of location information, easily accessed by an integer key, rather than having to use the key value itself to figure out spatial stuff.

To make that more concrete, let's say we have a 2 x 2 grid with cell edges at 0, 20, 40 and cell ids:

```
2 3
0 1
```



The `Grid` attributes (assuming a full distance matrix for now) then include:

```python
cells = ['Poly0', 'Poly1', 'Poly2', 'Poly3']
centroids = np.array([[10, 10], [30, 10] , [10, 30], [30,30]])
neighbours = [[1, 2], [0, 3], [3, 0], [2, 1]]
distances = np.array([[ 0.  , 20.  , 20.  , 28.28],
                      [20.  ,  0.  , 28.28, 20.  ],
                      [20.  , 28.28,  0.  , 20.  ],
                      [28.28, 20.  , 20.  ,  0.  ]])
```

So, accessing spatial information for a given cell index, then always uses the cell index and the `Grid` object.

```python
In []: # Get the Polygon object for cell 0
In []: grid.cells[0]
Out[]: 'Poly0'
In []: # Get the cell centroid
In []: grid.centroids[0]
Out[]: array([10, 10])
In []: # Get the ids of neighbours
In []: grid.neighbours[0]
Out[]: [1, 2]
In []: # Get distances to all other cells
In []: grid.distances[0]
Out[]: array([ 0.  , 20.  , 20.  , 28.28])
In []: # Get distance to specific cell
In []: grid.distances[0][2]
Out[]: 20.0
In []: # Or equivalently...
In []: grid.distances[0, 2]
Out[]: 20.0
In []: # Get distances to neighbours
In []: grid.distances[0, grid.neighbours[0]]
Out[]: array([20., 20.])
```

There is a further motivation in this from the data loading side - using integer cell ids is cleaner in a NetCDF file. We will support a range of data structures, but using integer rather than `str` or `tuple` keys simplifies the set of things we handle.

**Comment by dalonsoa** [comment]
This is much clearer. You have convinced me of the integer indexes as the best solution. I would not use a full distance matrix - that would be huge as you mentioned above - but otherwise the whole idea looks absolutely fine.

**Comment by davidorme** [comment]
Thanks - this has really helped me firm up what I'm after and how it should work. 

Using `networkx` could turn out to be crucial - I'm not sure how much of the graph theory stuff we need yet. I think at some point @TaranRallings is going to want to look at asymmetric travel costs over terrain and landscape resistance metrics, which are _very_ graphy!

I think I'll leave it as is for the moment - the interface would change a bit:

```python
neighbours = networkx.Graph({0: {1: {'dist': 20}, 2: {'dist': 20}},
                             3: {1: {'dist': 20}, 2: {'dist': 20}}})

# Access the neighbours and distances
In [212]: neighbours[0]
Out[212]: AtlasView({1: {'dist': 20}, 2: {'dist': 20}})
# Directly to distance
In [215]: g[1][3]
Out[215]: {'dist': 20}
```
