### ISSUE TITLE
Trivial Typos

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/virtual_rainforest#9]
This is just a holding issue to bundle up trivial documentation and docstring typos. If it needs rewording or reworking - just PR it now. If you have typos to add:

*  do use the checklist markdown format: `- [ ] Typo to fix here`. Note the spaces!
* do provide a direct link to the location: 
    * Viewing a doc in GitHub, make sure you are looking at the 'plain' view of the document using the  `<>` icon.
    * Select a line by clicking in the left margin
    * Click on the `...` menu that appears and `Copy permalink`
    * Note the change and paste the link. GitHub gets all clever about presenting it neatly :smile:

Once you have created a comment, you can come back and edit your comment to add new ones (or delete ones if they vanish). When this list gets long enough, we'll assign someone to run through them.

> **Warning**
> The permalink is to a **specific commit**, so line numbers may have changed in the current version of the file, but the link should give enough context to find the typo.

**Comment by vgro** [comment]
- [ ] 'devided' -> 'divided' https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/3d357fa4a4f80143783c87d7cd3fe959e265a1f2/source/virtual_rainforest/module_overview.md?plain=1#L113

**Comment by davidorme** [comment]
- [ ]  Promote Jacob to Dr. https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/3d357fa4a4f80143783c87d7cd3fe959e265a1f2/README.md?plain=1#L36

**Comment by jacobcook1995** [comment]
Not 100% if this counts as trivial, so feel free to disagree, but feel this change would aid navigating the documentation by reducing the number of folders called `virtual_rainforest`

- [ ] Rename folder virtual_rainforest/docs/source/virtual_rainforest/ to virtual_rainforest/docs/source/modules/

**Comment by davidorme** [comment]
This isn't being used any more.
