### ISSUE TITLE
Unpacking data from data system to initialise simulation run

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_rainforest#97]
**Is your feature request related to a problem? Please describe.**
Once the data system is setup we will need a way of reading from it and using the data stored in it to initialise a simulation run.

**Describe the solution you'd like**
Somewhat sketchy on what this would entail as the system for reading in and storing data is not yet established. However the data is stored it would need to be unpacked and used to setup the models. Probably in a specific `initialise_models_step`

**Describe alternatives you've considered**
Definitely need to use the data for initialisation eventually, so this seems unavoidable

**Comment by jacobcook1995** [comment]
The initialisation of the grid and data objects look sensible to me. I wonder if there should be a factory object to unpack the data object for model setup? Guess that mainly depends on where we want the sanity checking of data to occur though

**Comment by davidorme** [comment]
This is why that 'get-to-know-the-core'  meeting next week is timely 😄 The `load_from_config` validates all loaded data against a set of known core axes and the `Data` object then provides a method to report on validation. So an individual model setup could then do `data.on_core_axis('soil_structure', 'soil_depth')` to confirm that the variable aligns with the configured dimensions on that axis.

We could make those initial variables a formal part of the model structure (so a class attribute containing a list of required variables and axes) and then have the `BaseModel.__init__` run  `BaseModel.check_required_variables`. The model specific init might then need to do some bounds checking, but over in #135 there is some discussion of a general mechanism for setting bounds in the config that might apply here too?

**Comment by davidorme** [comment]
Incidentally, looking at the example code above, the `Grid`object is already within `Data`, so maybe that is where it is created - no need for it to float around as a separate thing, which reduces what needs to go in signatures. The grid is always accessed as `data.grid` and creation goes something like:

```
# Initialise the data object and load configured sources
data = core.data.Data(grid_config=config["core"]["grid"])
data.load_from_config(config["core"]["data"
```

**Comment by alexdewar** [comment]
> This is why that 'get-to-know-the-core' meeting next week is timely smile The `load_from_config` validates all loaded data against a set of known core axes and the `Data` object then provides a method to report on validation. So an individual model setup could then do `data.on_core_axis('soil_structure', 'soil_depth')` to confirm that the variable aligns with the configured dimensions on that axis.
> 
> We could make those initial variables a formal part of the model structure (so a class attribute containing a list of required variables and axes) and then have the `BaseModel.__init__` run `BaseModel.check_required_variables`. The model specific init might then need to do some bounds checking, but over in #135 there is some discussion of a general mechanism for setting bounds in the config that might apply here too?
> 
> So something like this:
> 
> ```python
> class BaseModel(ABC):
> 
>     # Define the required variables and axes (e.g. [('temperature', ('spatial', 'temporal'))])
>     required_variables: List[Tuple[str, Tuple[str]]] = []
> 
>     ...
> 
>     def check_required_variables(self):
> 
>         # Sentinel variables
>         axes_ok = True
>         bounds_ok = True
> 
>         # Loop over the required variables and axes
>         for var, axes in self.required_variables:
>             bound_check = self.data.check_bounds(var)
> 
>             if bound_check:
>                   LOGGER.info(f"Bounds ok on {var}")
>             else:
>                   LOGGER.error(f"Bounds not ok on {var}")
> 
>             bounds_ok &= bounds_check
> 
>             for axis in axes:
>                 axis_check = self.data.on_core_axis(var, axis)
>                 if axis_check:
>                     LOGGER.info(f"Variable {var} on axis {axis}")
>                 else:
>                     LOGGER.error(f"Variable {var} not on axis {axis}")
> 
>                 axes_ok &= axis_check
> 
>         if not axis_ok:
>             raise ValueError("Required variables not on core axes: see log")
>         if not bounds_ok:
>             raise ValueError("Required variables exceed configured bounds: see log")
> ```

Out of interest, isn't this check already done with the `jsonschema`? Do you need to recheck it?

**Comment by davidorme** [comment]
@alexdewar It's a fine line but the `jsonschema` stuff is used to validate model configuration options and the system we are discussing in #135 is used to check the bounds on data. Those bound checks could be at startup (as here) but could also be included in the timing loop to keep an eye on external or internal variables during execution. 

I _think_ that is a meaningful separation of two kinds of validation!

**Comment by alexdewar** [comment]
I'm probably missing something here, but isn't `jsonschema` and the bounds-checking all part of a "make sure input parameters are valid" step? E.g. if you have a temperature in Kelvin and the user provides a value of `-5.0` that's outside the bounds but it's also just nonsensical so it'd also probably be sensible to have `jsonschema` check this constraint too. I'm not familiar enough with `jsonschema` to know how to specify that kind of constraint, but to me it doesn't seem conceptually different from "the temperature config option must be a number".

If you need to revalidate your data structure again at some later stage (e.g. in your timing loop), can't you just do that with `jsonschema`?

**Comment by davidorme** [comment]
So, I think the workflow in mind is:

* The `jsonschema` and `config` stuff is about making sure the options on setting up a model are sane (and easily recorded in a simple file format) before the model even tries to use any data.
* A given variable isn't necessarily uniquely required by a single model - temperature for example - so the variables are then loaded into the central data store. 
* There is a `jsonschema` for the `data` configuration, but it is just specifying a data entry structure as a filepath for a variable (and a possible internal alias) and potentially bounds as described in #135.
* We could expand data `jsonschema` to an explicit set of named variables with bounds, but I think the content of that is is likely to be highly sensitive to different combinations of model choices and could be a nightmare to write and maintain.
* With the current setup, the models configure and then have a separate step (as in the sketch above) where they inspect the loaded shared data and see if it is all fit for purpose.


  is a difference between `config` options for a model - how many soil layers to use, which algorithm to choose

**Comment by alexdewar** [comment]
I'd be inclined to still try to use `jsonschema` wherever possible, i.e. models should provide their own schema for their own model-specific options, just to keep things consistent and clear.

If a model has its own additional requirements for *global* config options (on top of what the schema enforces), you can just check for that when you instantiate the model. Creating a load of boilerplate just to check whether input values are within a range just smells fishy to me: you can literally do that with one line of Python as it is. Not to mention, what if you want to check some other property of the config option besides whether it falls between two values? If e.g. your model requires that it be a multiple of 10 or something will you then have to extend your checking code?

Why not just do something like this:

```py
class MyModel:
    def __init__(config):
        init_temp = config["core"]["initial_temperature"]
        if init_temp < 10 or init_temp > 100:
             raise ValueError("MyModel requires the initial temperature to be between 10 and 100 degrees")
```

Your methods should really be sanity-checking their input values anyway, so I don't see what you get from trying to abstract this away, besides less readable code.

**Comment by davidorme** [comment]
This was partly about having to write possibly long lists of checks like that in the `__init__` and removing boilerplate.

With the sketch above, the `BaseModel.__init__()` could just do this:

```python
def __init__(self, data):
    ...
    self.check_required_variables()
    ...
```

And then all a given real model has to do is populate `self.required_variables` appropriately.

Having said that - I've realised the bounds checking is in completely misplaced in my sketch. There is absolutely no point in every model checking bounds. What should happen is that if bounds are defined on a variable in the configuration, then the `Data` object should check them on load and as requested during runtime.

**Comment by davidorme** [comment]
I'm being dim. There's a key reason we **can't** use `jsonschema` for this.  You could only do that if the actual data values were present in the `toml` file being validated against the schema, and they're not. The `data` configuration provides paths to netcdf files and those have to be loaded into the data object before the values can be bounds checked.

**Comment by alexdewar** [comment]
Ohhh so it's about validating actual data values, not parameters.

Either way, I think what I said still stands. Writing bespoke classes that just do bounds checks on data is just going to produce a lot of ugly boilerplate. Just let models do their own bespoke input checking; that'll make things more flexible anyway.

**Comment by davidorme** [comment]
I disagree. Models should of course be able to do bespoke checking, but the bounds we are discussing here are intended to be simulation-wide limits on what are sane values for variables, many of which are likely to be shared across multiple models. Having those simulation-wide limits checked centrally means the bounds checks on input variables are done once at startup and then those `Model.__init__` can rely on the contents to be within bounds.

**Comment by alexdewar** [comment]
Ah, ok. I forgot you're sharing these values between models.

**Comment by davidorme** [comment]
But that does raise the important point that the implementation of this should probably **insist** on bounds being provided for data loaded from file to run the simulation. That doesn't seem unreasonable at all, although doesn't guard against a user setting stupid bounds though.

I think in the first instance, we just let stupid inputs fail stupidly, but... 

In the future I could see individual BaseModel subclasses having more finicky requirements: PlantModelGreenhouse might represent unusual biology that only makes sense when atmospheric CO2 is over 500ppm.  If the individual model classes have a class attribute listing the required variable, axes and bounds, then we could access those in the main loop before even needing to init instances and check that bounds are compatible across models and data before doing anything. But I'm pretty sure that is premature!
